language: bash

services:
  - docker

group: bluezone

dist: xenial

sudo: required
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    packages:
      - docker-ce

before_install:
  - echo "Killing auto-updates to avoid apt lock conflicts";
  - sudo systemctl stop apt-daily.service;
  - sudo systemctl stop apt-daily.timer;
  - sudo systemctl stop apt-daily-upgrade.service;
  - sudo systemctl stop apt-daily-upgrade.timer;
  - sudo apt-get install -y dnsutils
  - sudo chgrp travis /var/run/docker.sock
  - docker version
  
jobs:
  include:
    - stage: build-push-images
      os: linux
      script:
      - uname -a
      - cat /etc/issue
      - wget `curl -s https://api.github.com/repos/openshift/origin/releases/latest | jq -r ".assets[] | select(.name | test(\"linux-64bit\")) | .browser_download_url" | grep -i client-tools`
      - tar xvfz `ls openshift-origin-client-tools-*.tar.gz` --strip-components=1 -C $HOME/bin
      - oc version    
    - stage: test
      if: tag IS present
      script:
      - echo "Tag is present"
      - ./setupAppNavTestEnv.sh $OCP_URL $OCP_USER $OCP_PWD $DOCKER_USER

    
    
